
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/gianmarco/.mplab/app-finder/apps/cmake/v3.31.6/cmake-3.31.6-macos-universal/CMake.app/Contents/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Darwin - 24.4.0 - arm64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/gianmarco/.mplab/app-finder/apps/cmake/v3.31.6/cmake-3.31.6-macos-universal/CMake.app/Contents/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Darwin - 24.4.0 - arm64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/gianmarco/.mplab/app-finder/apps/cmake/v3.31.6/cmake-3.31.6-macos-universal/CMake.app/Contents/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Darwin - 24.4.0 - arm64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/gianmarco/.mplab/app-finder/apps/cmake/v3.31.6/cmake-3.31.6-macos-universal/CMake.app/Contents/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Darwin - 24.4.0 - arm64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/gianmarco/.mplab/app-finder/apps/cmake/v3.31.6/cmake-3.31.6-macos-universal/CMake.app/Contents/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Darwin - 24.4.0 - arm64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/gianmarco/.mplab/app-finder/apps/cmake/v3.31.6/cmake-3.31.6-macos-universal/CMake.app/Contents/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Darwin - 24.4.0 - arm64
